{% set name = "django-simple-captcha" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9df5cf24e38b91af62d601f8e5189b0f6d28dbaa55a363a8b9d727703f9c35de

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2
    - pillow >=6.2.0
    - django-ranged-response =0.2.0

test:
  imports:
    - captcha
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/mbi/django-simple-captcha
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Django application to add captcha images to any Django form.
  description: |
    Django Simple Captcha is an extremely simple, yet highly customizable
    Django application to add captcha images to any Django form.
  doc_url: https://django-simple-captcha.readthedocs.io/en/latest/
  dev_url: https://github.com/mbi/django-simple-captcha

extra:
  recipe-maintainers:
    - swainn
