{% set name = "django-simple-captcha" %}
{% set version = "0.5.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e1fcc4f4005f7d69ee7a2e59a7e863b5d3918f36a85a4d811498984aecc48ce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >=2.2
    - pillow >=6.2.0
    - django-ranged-response =0.2.0
    - six

test:
  imports:
    - captcha
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mbi/django-simple-captcha
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Django application to add captcha images to any Django form.
  description: |
    Django Simple Captcha is an extremely simple, yet highly customizable
    Django application to add captcha images to any Django form.
  doc_url: https://django-simple-captcha.readthedocs.io/en/latest/
  dev_url: https://github.com/mbi/django-simple-captcha

extra:
  recipe-maintainers:
    - swainn
