{% set name = "django-simple-captcha" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d188516d326fadd2d5ad076eb89649d55c02cabafe3fdcc2154ac18e9f6d4b97

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - django >=4.2
    - pillow >=6.2.0
    - django-ranged-response =0.2.0

test:
  imports:
    - captcha
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mbi/django-simple-captcha
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Django application to add captcha images to any Django form.
  description: |
    Django Simple Captcha is an extremely simple, yet highly customizable
    Django application to add captcha images to any Django form.
  doc_url: https://django-simple-captcha.readthedocs.io/en/latest/
  dev_url: https://github.com/mbi/django-simple-captcha

extra:
  recipe-maintainers:
    - swainn
